update action to work manually

diff --git a/.github/workflows/build_devrelease.yml b/.github/workflows/build_devrelease.yml
--- a/.github/workflows/build_devrelease.yml
+++ b/.github/workflows/build_devrelease.yml
@@ -1,51 +1,35 @@
 name: build_devrelease
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - pre-release
 
 jobs:
-  # bump the version and build the changelog
-  version_and_changelog:
+  version_check:
     runs-on: ubuntu-20.04
     env:
       GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
     steps:
-      # fail out if this is not a merge commit
-      - name: ensure merge
-        if: ${{ !startsWith(github.event.head_commit.message, 'Merge') }}
-        run: exit 1
-
       - name: checkout version
         uses: actions/checkout@v4.1.4
         with: 
           fetch-depth: 0
 
-      - name: get last merge
-        id: last_merge
-        shell: bash
-        run: |
-          echo "short_hash=$(echo $(git log --oneline --merges -n 10 | grep -m2 "pull request" | tail -n1 | cut -d' ' -f1))" >> $GITHUB_OUTPUT
-
-      - run: |
-          echo "Last Merge: ${{ steps.last_merge.outputs.short_hash }}"
-
-      # wait for any previous versions to be tagged and committed
-      - uses: lewagon/wait-on-check-action@v1.3.4
+      - id: latest_package
         continue-on-error: true
+        uses: pozetroninc/github-action-get-latest-release@master
         with:
-          ref: ${{ steps.last_merge.outputs.short_hash }}
-          check-name: 'version_and_changelog'
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          wait-interval: 30
-          allowed-conclusions: success,skipped,cancelled,failure
+          repository: HDR-Development/HDR-DevReleases
+          token: ${{ secrets.RELEASE_TOKEN }}
+    
+      # fail out if there's already a release for this commit
+      - name: ensure one build per sha
+        if: ${{ contains(steps.latest_package.outputs.release, github.sha) }}
+        run: exit 1
 
   plugin_build:
     env:
       PLUGIN_NAME: hdr
     runs-on: ubuntu-20.04
-    needs: version_and_changelog
+    needs: version_check
     container: 
       image: hewdrawremix/hewdraw-builder:latest
     steps:
